swagger: '2.0'
info:
  description: "Inventory Control API"
  version: '1.0'
  title: "Inventory Control API"
host: localhost:8080
basePath: /inventory-control
schemes:
  - http
paths:
  '/products':
    post:
      tags:
        - Products
      description: Create a new product
      parameters:
        - name: ProductPostRequest
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProductPostRequest'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          schema:
            type: array
            items:
              $ref: '#/definitions/ClientError'
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
    get:
      tags:
        - Products
      description: Retrieve all products
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductsResponse'
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
  '/products/{id}':
    get:
      tags:
        - Products
      description: Retrieve an specific product by id
      parameters:
        - name: "id"
          in: "path"
          description: "ID of goal"
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ProductsResponse'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
    put:
      tags:
        - Products
      description: Update a product by id
      parameters:
        - name: id
          in: path
          description: product id
          required: true
          type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          schema:
            type: array
            items:
              $ref: '#/definitions/ClientError'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
    patch:
      tags:
        - Products
      description: Partial update a product by id
      parameters:
        - name: id
          in: path
          description: product id
          required: true
          type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          schema:
            type: array
            items:
              $ref: '#/definitions/ClientError'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
    delete:
      tags:
        - Products
      description: Remove um goal pelo id.
      parameters:
        - name: id
          in: path
          description: product id
          required: true
          type: string
      responses:
        '204':
          description: No Content
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout
definitions:
  ClientError:
    type: object
    properties:
      code:
        type: string
        description: Error code
      message:
        type: string
        description: Error message
  ProductPostRequest:
    required:
      - "type"
      - "deadline"
      - "expectedQuantity"
      - "performedQuantity"
      - "reward"
      - "isCompleted"
    type: object
    properties:
      name:
        type: string
        description: product name
      category:
        type: string
        description: product type
        enum:
          - HARDWARE
          - GAMES
          - PC
      stock_quantity:
        type: number
      description:
        type: string
        description: product description
      image:
        type: string
        description: product image base64
      price:
        type: number
        description: product price
      discount:
        type: integer
        description: product discount percentage
  ProductsResponse:
    type: object
    properties:
      id:
        type: string
        description: product id
      name:
        type: string
        description: product name
      category:
        type: string
        description: product type
        enum:
          - HARDWARE
          - GAMES
          - PC
      updated_at:
        type: string
        description: updated date (yyyy-MM-dd HH:mm:ss)
      created_at:
        type: string
        description: created date (yyyy-MM-dd HH:mm:ss)
      stock_quantity:
        type: number
      description:
        type: string
        description: product description
      image:
        type: string
        description: product image base64
      price:
        type: number
        description: product price
      discount:
        type: integer
        description: product discount percentage
      